# Generated by Django 5.2.7 on 2025-11-10 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Model', models.CharField(max_length=5)),
                ('Nif', models.CharField(max_length=20, null=True)),
                ('Designation', models.CharField(max_length=100)),
                ('Adresse', models.CharField(max_length=100, null=True)),
                ('Telephone', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Refdoc', models.CharField(max_length=100, null=True)),
                ('Profil', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('Operateur', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=50)),
                ('Numero', models.CharField(max_length=50)),
                ('Obs', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Nif', models.CharField(max_length=20)),
                ('Rccm', models.CharField(max_length=30, null=True)),
                ('Designation', models.CharField(max_length=100)),
                ('Devise', models.CharField(max_length=5)),
                ('Activité', models.CharField(max_length=100)),
                ('Adresse', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Site', models.CharField(max_length=100, null=True)),
                ('Logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeTaxation',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=5)),
                ('Designation', models.CharField(max_length=30)),
                ('Taux', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Libelle', models.IntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeActeur',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=5)),
                ('Libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFacture',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=5)),
                ('Libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompteClient',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.acteur')),
                ('Compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.compte')),
            ],
        ),
        migrations.CreateModel(
            name='CompteEntreprise',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.compte')),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Montant', models.IntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('DateFin', models.DateField(null=True)),
                ('Obs', models.CharField(max_length=100, null=True)),
                ('Compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.compteentreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Heure', models.TimeField(auto_now_add=True)),
                ('Type', models.CharField(max_length=50)),
                ('Devise', models.CharField(max_length=5)),
                ('Montant', models.IntegerField()),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.acteur')),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Libelle', models.CharField(max_length=30)),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='acteur',
            name='Entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('Uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('RN', models.CharField(max_length=30, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Heure', models.TimeField(auto_now_add=True)),
                ('Montant', models.IntegerField()),
                ('Devise', models.CharField(max_length=5)),
                ('ModeFacture', models.CharField(max_length=5)),
                ('ModePaiement', models.CharField(max_length=30)),
                ('NatureAvoir', models.CharField(max_length=30, null=True)),
                ('ReferenceAvoir', models.CharField(max_length=30, null=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.acteur')),
                ('Compte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.compteclient')),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='DataDgi',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codeDEFDGI', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=100)),
                ('counters', models.CharField(max_length=100)),
                ('dateTime', models.CharField(max_length=100)),
                ('qrcode', models.CharField(max_length=100)),
                ('Facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Texte', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Heure', models.TimeField(auto_now_add=True)),
                ('Facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Type', models.CharField(max_length=5)),
                ('Designation', models.CharField(max_length=50)),
                ('Prix', models.IntegerField()),
                ('Devise', models.CharField(max_length=5)),
                ('Mesure', models.CharField(max_length=30, null=True)),
                ('Photo', models.ImageField(upload_to='')),
                ('Mode', models.CharField(max_length=5)),
                ('Categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.categorie')),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
                ('Groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.groupetaxation')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDevis',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Quantite', models.IntegerField()),
                ('Montant', models.IntegerField()),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.article')),
                ('Devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.devis')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFacture',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Quantite', models.IntegerField()),
                ('Montant', models.IntegerField()),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.article')),
                ('Facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Heure', models.TimeField(auto_now_add=True)),
                ('Titre', models.CharField(max_length=100)),
                ('Texte', models.TextField()),
                ('Photo', models.ImageField(upload_to='')),
                ('Lecture', models.BooleanField(default=False)),
                ('Entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Profil', models.ImageField(upload_to='')),
                ('SuperAdmin', models.BooleanField(default=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='Operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.operateur'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Heure', models.TimeField(auto_now_add=True)),
                ('Type', models.CharField(max_length=30)),
                ('Element', models.CharField(max_length=30)),
                ('Table', models.CharField(max_length=30)),
                ('Obs', models.CharField(max_length=100, null=True)),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
                ('Operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.operateur')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Heure', models.TimeField(auto_now_add=True)),
                ('Mode', models.CharField(max_length=30)),
                ('Devise', models.CharField(max_length=5)),
                ('Taux', models.IntegerField(null=True)),
                ('Montant', models.IntegerField()),
                ('Statut', models.CharField(max_length=30)),
                ('Solde', models.CharField(max_length=30)),
                ('Compte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.compteclient')),
                ('Facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.facture')),
                ('Operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.operateur')),
            ],
        ),
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Designation', models.CharField(max_length=100)),
                ('Key', models.CharField()),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='operateur',
            name='PointVente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.pointvente'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Heure', models.TimeField(auto_now_add=True)),
                ('PrixUnitaire', models.IntegerField()),
                ('Devise', models.CharField(max_length=5)),
                ('Taux', models.IntegerField(null=True)),
                ('Quantite', models.IntegerField()),
                ('Montant', models.IntegerField()),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.article')),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
                ('Fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.acteur')),
            ],
        ),
        migrations.CreateModel(
            name='StyleFacture',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Primary_color', models.CharField(max_length=50)),
                ('Filigrane', models.ImageField(null=True, upload_to='')),
                ('Police', models.CharField(max_length=50)),
                ('Border_color', models.CharField(max_length=50)),
                ('Premiere_ligne', models.CharField(max_length=50)),
                ('Deuxieme_ligne', models.CharField(max_length=50)),
                ('CompteClient', models.BooleanField(default=True)),
                ('CompteEntreprise', models.BooleanField(default=True)),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='TaxeSpecifique',
            fields=[
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=100)),
                ('Taux', models.IntegerField()),
                ('Entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Taxe_specifique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.taxespecifique'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.typeacteur'),
        ),
        migrations.AddField(
            model_name='facture',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfe_facturation.typefacture'),
        ),
    ]
