from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns =[
    path('', views.login, name='login'),
    path('password/', views.forgot_password, name='forgot'),
    path('login/', views.authentification, name='authentification'),
    path('home/', views.home, name='home'),
    path('articles/', views.liste_articles, name='articles'),
    path('categorie/', views.nouvelle_categorie, name='categorie'),
    path('article/', views.nouvel_article, name='article'),
    path('delete_article/', views.delete_article, name='delete_article'),
    path('modifier_article/', views.modif_article, name='modif_article'),
    path('photo_article/', views.photo_article, name='photo_article'),
    path('infos_article/', views.infos_article, name='infos_article'),
    path('detail_article/', views.details_article, name='detail_article'),
    path('clients/', views.liste_clients, name='clients'),
    path('client/', views.nouveau_client, name='client'),
    path('delete_client/', views.delete_client, name='delete_client'),
    path('modifier_client/', views.modif_client, name='modif_client'),
    path('infos_client/', views.infos_client, name='infos_client'),
    path('photo_client/', views.photo_client, name='photo_client'),
    path('stock/', views.liste_stock, name='stock'),
    path('nouveau_stock/', views.nouveau_stock, name='nouveau_stock'),
    path('delete_stock/', views.delete_stock, name='delete_stock'),
    path('modifier_stock/', views.modif_stock, name='modif_stock'),
    path('infos_stock/', views.modif_infos_stock, name='infos_stock'),
    path('details_stock/', views.details_stock, name='details_stock'),
    path('fournisseurs/', views.liste_fournisseurs, name='fournisseurs'),
    path('fournisseur/', views.nouveau_fournisseur, name='fournisseur'),
    path('client_fournisseur/', views.client_fournisseur, name='client_fournisseur'),
    path('delete_fournisseur/', views.delete_fournisseur, name='delete_fournisseur'),
    path('modifier_fournisseur/', views.modif_fournisseur, name='modif_fournisseur'),
    path('photo_fournisseur/', views.photo_fournisseur, name='photo_fournisseur'),
     path('infos_fournisseur/', views.infos_fournisseur, name='infos_fournisseur'),
    path('details_fournisseur/', views.details_fournisseur, name='details_fournisseur'),
    path('facturation/', views.facturation, name='facturation'),
    path('detail/', views.detail_commande, name='detail'),
    path('facture/', views.nouvelle_facture, name='facture'),
    path('mails/', views.envoyer_mail, name='email'),
    path('mails/envoyer', views.mail_envoye, name='envoie'),
    path('paiement/', views.paiement, name='paiement'),
    path('paiement/supprimer', views.delete_paiement, name='delete_paiement'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)